site_name: A.I.G (AI-Infra-Guard) 文档
theme:
  name: material
  palette:
    # Palette toggle for light and dark modes
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  icon:
    repo: fontawesome/brands/github-alt
repo_url: https://github.com/Tencent/AI-Infra-Guard
repo_name: Tencent/AI-Infra-Guard

nav:
  - '欢迎': 'index.md'
  - '快速开始': 'getting-started.md'
  - 'AI基础设施安全扫描': 'ai-infra-scan.md'
  - 'MCP Server安全扫描': 'mcp-scan.md'
  - 'Prompt安全评测': 'prompt-eval.md'
  - '实践案例': 'case-studies.md'
  - '贡献指南': 'contributing.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html